# 2. cluster-role-binding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: demo-admin-binding
subjects:
- kind: User
  name: DemoUser-Admin  # <--- THIS IS THE REQUIRED MATCHING VALUE
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: demo-admin-role
  apiGroup: rbac.authorization.k8s.io