apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-app-sa
  namespace: default
  annotations:
    # ⚠️ Use the ARN of the role you just created in Step 2
    eks.amazonaws.com/role-arn: arn:aws:iam::266735810620:role/MyLeastPrivilegeS3Role